sudo: required

services:
  - docker
  
language: go

go:
  - 1.7.x

env:
  global:
    - GO_ENV=test

install: 
  - make setup-ci

script: 
  - make test
  - make goveralls

after_success:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - make dockerize