sudo: required

services:
  - docker
  
language: go

node_js: 6.10.0
go: 1.7.5

env:
  global:
    - GO_ENV=test
    - NODE_ENV=test

install: 
  - make setup-ci

script: 
  - npm run lint
  - npm run build  
  - make test
  - make goveralls

after_success:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - make dockerize