sudo: required

services:
  - docker
  
language: go

go: 1.8

env:
  global:
    - GO_ENV=test
    - NODE_ENV=test

install: 
  - nvm install "$(jq -r '.engines.node' package.json)"
  - npm i -g yarn
  - go get github.com/joho/godotenv/cmd/godotenv
  - docker-compose up -d pgtest
  - yarn

script: 
  - npm run lint
  - npm run build  
  - make test
  - make coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - make dockerize