sudo: required

services:
  - docker
  
language: go

go: 1.8

env:
  global:
    - GO_ENV=test
    - NODE_ENV=test

install: 
  - go get github.com/mattn/goveralls
  - go get github.com/joho/godotenv/cmd/godotenv
  - npm install

script: 
  - npm run lint
  - npm run build  
  - make test
  - godotenv -f .test.env goveralls -service=travis-ci

after_success:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - make dockerize