sudo: required

services:
  - docker
  
language: go

go:
  - 1.7.x

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

install: make setup-ci

script: 
  - make run-ci
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 make build
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=wecanhearyou/wchy-api
  - export TAG=`if [ "$TRAVIS_BRANCH" == "dev" ]; then echo "staging"; else echo "latest" ; fi`
  - docker build -f Dockerfile -t $REPO:$TAG .
  - docker push $REPO