sudo: required

services:
  - docker
  
language: go

go: 1.8

env:
  global:
    - GO_ENV=test
    - NODE_ENV=test

install: 
  - make setup-ci
  - npm install

script: 
  - npm run lint
  - npm run build  
  - make test
  - make goveralls

after_success:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - make dockerize