sudo: required

services:
  - docker
  
language: go

go:
  - 1.7.x

env:
  global:
    - GO_ENV=test

install: 
  - make setup-ci

script: 
  - make test
  - make goveralls
  - make dockerize

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - make dockerize